### ISSUE TITLE
code

### ISSUE THREAD

**Issue by flynnamy** [limuloo/PyDIff#1]
Hi,could you please share the code including model weights for test? @limuloo

**Comment by limuloo** [comment]
> Hi,could you please share the code including model weights for test? @limuloo

Of course, I am currently in the process of organizing the code for this project and will soon provide comprehensive training and testing code, along with pre-trained weights. This process will be completed expeditiously.

**Comment by danielajisafe** [comment]
Thanks for your great work! In the meantime, please can you share the supplemental document to the main paper? That would be a good read too.

**Comment by limuloo** [comment]
> Thanks for your great work! In the meantime, please can you share the supplemental document to the main paper? That would be a good read too.

Thank you for your interest in our study. To access the supplementary material, please refer to the provided link below.

https://drive.google.com/file/d/1_c5nM_bQkdDMWASpY-3aoxf_YYzfWCwf/view?usp=sharing

**Comment by Levijpg** [comment]
Hi, I read your paper recently and found it was so inspiring. I'm honestly interested in this work, so I'm afraid to ask if you could share the code of this work, this would be so helpful. @limuloo

**Comment by limuloo** [comment]
> Hi, I read your paper recently and found it was so inspiring. I'm honestly interested in this work, so I'm afraid to ask if you could share the code of this work, this would be so helpful. @limuloo

Thank you for expressing your interest in our research. We are pleased to inform you that the code associated with our study will be made available in the near future.

**Comment by Sn-121** [comment]
Hi,your paper is so great,could you please share the code of this work?thanks.

**Comment by limuloo** [comment]
> 

Thank you for acknowledging our research. We have made the code openly accessible for the community.

**Comment by limuloo** [comment]
> Hi,your paper is so great,could you please share the code of this work?thanks.

Thank you for acknowledging our research. We have made the code openly accessible for the community.
