### ISSUE TITLE
PSNR without Kind align

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [limuloo/PyDIff#10]
Hi!

Wondering the PSNR score without Kind align.
Are the scores recorded in the paper produced with Kind align?

Thanks a lot.

**Comment by limuloo** [comment]
Yes.
For a better comparison, many SOTA methods in the current LOL benchmark (such as the second-ranked LLFLOW) adjust the brightness of the image output by the network to be consistent with GT to compare the restoration of texture details.

**Comment by limuloo** [comment]
Yes.
For a better comparison, many SOTA methods in the current LOL benchmark (such as the second-ranked LLFLOW) adjust the brightness of the image output by the network to be consistent with GT to compare the restoration of texture details and color.

**Comment by limuloo** [comment]
You can easily set 'use_kind_align' as false in 'options/infer.yaml' to get result without Kind align.
