### ISSUE TITLE
Where is the coefficient shift_x_recon_detach_range from?

### ISSUE THREAD

**Issue by Maydaybye** [limuloo/PyDIff#12]
Thank you for you great work, but still I have a problem that where is the coefficient 'shift_x_recon_detach_range' come from.
Looking forward to your reply
![QUESTION](https://github.com/limuloo/PyDIff/assets/75834797/984b78de-ba57-44da-8e28-990f682e74e1)

**Comment by limuloo** [comment]
In actual training, this value is not used. 
This may be a value I randomly set early on to simulate the color difference that may occur during the inference process.

**Comment by Maydaybye** [comment]
Thank you very much. Have a nice day!
