### ISSUE TITLE
Confusion about loss.

### ISSUE THREAD

**Issue by Maydaybye** [limuloo/PyDIff#13]
Hi, I'm a little confused about the following regarding the calculation of loss.
1. the paper says sqrt(1-α¯t/α¯t) > γ to do gradient descent for color offset, but why does it count the loss every time in the first image where the red line is drawn?
2. Is cs_on_shift calculating the color shift in the second image? cs_on_shift is true, the input to color_fn is x_start_shift.
  When cs_on_shift is false, the input to color_fn is self.x_recon_detach. I think both inputs are essentially trying to minimize the difference from the ground truth!
  What is the difference between them?
![20231030175429](https://github.com/limuloo/PyDIff/assets/75834797/410dc09a-96af-4d33-8ffe-2c531b8dc319)

Really confused      /_ \   
 Looking forward to your help.

**Comment by limuloo** [comment]
(1) During the final implementation, we found that there is not much performance difference between optimizing the global corrector at all times and optimizing only when sqrt(1-α¯t/α¯t) > γ. However, during inference, this condition must still be met. 
Anyway, you can set gamma_limit_train as 1.0 to be consistent with the paper.
(2) x_recon_detach may have noise. x_start_shift has no noise, which only has color shift.

**Comment by Maydaybye** [comment]
Thanks for your patience and detailed answers!
