### ISSUE TITLE
quick test

### ISSUE THREAD

**Issue by Amore-HDU** [limuloo/PyDIff#2]
Hello,
I'd want to know how to test. when I run “CUDA_VISIBLE_DEVICES=0 python pydiff/train.py -opt options/infer.yaml", it looks like going train.

**Comment by Amore-HDU** [comment]
@limuloo

**Comment by Amore-HDU** [comment]
@limuloo thanks

**Comment by Xing-lil** [comment]
I have the same question. How can I solve it?

**Comment by Amore-HDU** [comment]
你好，我是毛礼建，您发送的东西我已经收到！

**Comment by zxp771** [comment]
@Amore-HDU @limuloo I got the same question.

Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2023.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2023.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PyDIff-main\PyDiff\pydiff\train.py", line 11, in <module>
    train_pipeline(root_path)
  File "D:\PyDIff-main\BasicSR-light\basicsr\train.py", line 120, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "D:\PyDIff-main\BasicSR-light\basicsr\train.py", line 48, in create_train_val_dataloader
    total_epochs = math.ceil(total_iters / (num_iter_per_epoch))
ZeroDivisionError: division by zero
python-BaseException

Process finished with exit code 1

**Comment by superxianyuwang** [comment]
@limuloo Hello！I got the same question: ZeroDivisionError: division by zero. How can I solve them?

**Comment by Amore-HDU** [comment]
你好，我是毛礼建，您发送的东西我已经收到！

**Comment by limuloo** [comment]
> @limuloo Hello！I got the same question: ZeroDivisionError: division by zero. How can I solve them?

what's the path of your LOL dataset?

**Comment by superxianyuwang** [comment]
> 

/PyDiff/dataset/LOLdataset

**Comment by superxianyuwang** [comment]
> > @limuloo Hello！I got the same question: ZeroDivisionError: division by zero. How can I solve them?
> 
> what's the path of your LOL dataset?

//PyDiff/dataset/LOLdataset/eval15

**Comment by limuloo** [comment]
> > > @limuloo Hello！I got the same question: ZeroDivisionError: division by zero. How can I solve them?
> > 
> > 
> > what's the path of your LOL dataset?
> 
> //PyDiff/dataset/LOLdataset/eval15

have you put the training data into //PyDiff/dataset/LOLdataset/our485?

**Comment by jrcyyzb** [comment]
> 你好，我是毛礼建，您发送的东西我已经收到！

师兄，有训练代码吗，发我一份

**Comment by limuloo** [comment]
When running “CUDA_VISIBLE_DEVICES=0 python pydiff/train.py -opt options/infer.yaml", the training process will actually be skipped and inference will go directly.

**Comment by Klawens** [comment]
Same problem if you don't fill the right train set path

**Comment by Amore-HDU** [comment]
你好，我是毛礼建，您发送的东西我已经收到！
