### ISSUE TITLE
time

### ISSUE THREAD

**Issue by zhenyuan1234** [limuloo/PyDIff#4]
How long did it take to train the model?

**Comment by finnn00** [comment]
Hello
Can I get the faster configuration for experiments?
Now I am working on the condition of gpu=1，  batch size=4, May I ask how many days it would take to retrain your model? 
Also can I get the FPS code too?
Looking for ur reply! My email: finn951017@outlook.com

**Comment by limuloo** [comment]
@finnn00 To enable PyDiff to train on a single GPU, the PyDiff/options/train_v2.yaml file can be consulted.
