### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.utils'

### ISSUE THREAD

**Issue by zjx1277** [limuloo/PyDIff#5]
I tried to use the model to inference, 
CUDA_VISIBLE_DEVICES=0 python pydiff/train.py -opt options/infer.yaml
but it shows ModuleNotFoundError: No module named 'scripts.utils'

**Comment by limuloo** [comment]
Did you successfully run the "BASICSR_EXT=True sudo $(which python) setup.py develop" command in the "BasicSR-light" and "PyDiff" directories?

**Comment by zjx1277** [comment]
When I run the command you've mentioned, it shows another error：/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))

**Comment by zjx1277** [comment]
I've installed 'ninja' package, but when I run the commed that you mentioned, it shows: 
---------------------------------------------------------------
running develop
running egg_info
writing basicsr.egg-info/PKG-INFO
writing dependency_links to basicsr.egg-info/dependency_links.txt
writing top-level names to basicsr.egg-info/top_level.txt
reading manifest file 'basicsr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'basicsr.egg-info/SOURCES.txt'
/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
running build_ext
Creating /home/ubuntu/anaconda3/lib/python3.8/site-packages/basicsr.egg-link (link to .)
basicsr 1.3.4.4 is already the active version in easy-install.pth

Installed /home/ubuntu/pythonProject/PyDIff-main/BasicSR-light
Processing dependencies for basicsr==1.3.4.4
Finished processing dependencies for basicsr==1.3.4.4
--------------------------------------------------------------------
it this correctly installed?

**Comment by limuloo** [comment]
> ## I've installed 'ninja' package, but when I run the commend that you mentioned, it shows:
> running develop running egg_info writing basicsr.egg-info/PKG-INFO writing dependency_links to basicsr.egg-info/dependency_links.txt writing top-level names to basicsr.egg-info/top_level.txt reading manifest file 'basicsr.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' writing manifest file 'basicsr.egg-info/SOURCES.txt' /home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend. warnings.warn(msg.format('we could not find ninja.')) running build_ext Creating /home/ubuntu/anaconda3/lib/python3.8/site-packages/basicsr.egg-link (link to .) basicsr 1.3.4.4 is already the active version in easy-install.pth
> 
> ## Installed /home/ubuntu/pythonProject/PyDIff-main/BasicSR-light
> Processing dependencies for basicsr==1.3.4.4
> Finished processing dependencies for basicsr==1.3.4.4
> it this correctly installed?

This does not display an error, you can continue to execute subsequent commands to see if the inference is ok.

**Comment by zjx1277** [comment]
I created a new conda environment, installed all of the packages, but still report same error.........   xD

**Comment by limuloo** [comment]
> I created a new conda environment, installed all of the packages, but still report same error......... xD

Can you share the all commands you run to start with creating the environment?

**Comment by zjx1277** [comment]
1) first create conda environment: _conda create -n PyDiff python=3.7_
2) then acvitate it, and run: _conda install pytorch==1.7.0 torchvision torchaudio cudatoolkit=11.0 -c pytorch_
3) cd BasicSR-light
4) For some reason, I have to chang pip source to install pip packages: _pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple_ 
5) cd ../PyDiff
6) same as Step 4)
7) after all the packages installed, run the "BASICSR_EXT=True sudo $(which python) setup.py develop" command in the "BasicSR-light" and "PyDiff" directories

**Comment by limuloo** [comment]
> 1. first create conda environment: _conda create -n PyDiff python=3.7_
> 2. then acvitate it, and run: _conda install pytorch==1.7.0 torchvision torchaudio cudatoolkit=11.0 -c pytorch_
> 3. cd BasicSR-light
> 4. For some reason, I have to change pip source to install pip packages: _pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple_
> 5. cd ../PyDiff
> 6. same as Step 4), but the pip package"_tb-nightly_" does not exist in the Tsinghua University Source Lib, so I use _pip install tb-nightly -i https://mirrors.aliyun.com/pypi/simple_  to install it
> 7. after all the packages installed, run the _"BASICSR_EXT=True sudo $(which python) setup.py develop"_ command in the _"BasicSR-light"_ and _"PyDiff"_ directories

you shold run "BASICSR_EXT=True sudo $(which python) setup.py develop" in "BasicSR-light"  !!! before step 5 !!!

**Comment by limuloo** [comment]
> 1. first create conda environment: _conda create -n PyDiff python=3.7_
> 2. then acvitate it, and run: _conda install pytorch==1.7.0 torchvision torchaudio cudatoolkit=11.0 -c pytorch_
> 3. cd BasicSR-light
> 4. For some reason, I have to change pip source to install pip packages: _pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple_
> 5. cd ../PyDiff
> 6. same as Step 4), but the pip package"_tb-nightly_" does not exist in the Tsinghua University Source Lib, so I use _pip install tb-nightly -i https://mirrors.aliyun.com/pypi/simple_  to install it
> 7. after all the packages installed, run the _"BASICSR_EXT=True sudo $(which python) setup.py develop"_ command in the _"BasicSR-light"_ and _"PyDiff"_ directories

You also have to make sure that you are in the path of PyDIff/PyDiff/ when you perform inference, and then execute "CUDA_VISIBLE_DEVICES=0 python pydiff/train.py -opt options/infer.yaml"

**Comment by zjx1277** [comment]
If I run BASICSR_EXT=True sudo $(which python) setup.py develop" in "BasicSR-light" before step 5, it shows
![image](https://github.com/limuloo/PyDIff/assets/80657281/2c7487f8-229e-4399-9afc-d28da4720a36)

**Comment by zjx1277** [comment]
> > 1. first create conda environment: _conda create -n PyDiff python=3.7_
> > 2. then acvitate it, and run: _conda install pytorch==1.7.0 torchvision torchaudio cudatoolkit=11.0 -c pytorch_
> > 3. cd BasicSR-light
> > 4. For some reason, I have to change pip source to install pip packages: _pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple_
> > 5. cd ../PyDiff
> > 6. same as Step 4), but the pip package"_tb-nightly_" does not exist in the Tsinghua University Source Lib, so I use _pip install tb-nightly -i https://mirrors.aliyun.com/pypi/simple_  to install it
> > 7. after all the packages installed, run the _"BASICSR_EXT=True sudo $(which python) setup.py develop"_ command in the _"BasicSR-light"_ and _"PyDiff"_ directories
> 
> You also have to make sure that you are in the path of PyDIff/PyDiff/ when you perform inference, and then execute "CUDA_VISIBLE_DEVICES=0 python pydiff/train.py -opt options/infer.yaml"

I'm sure that I was in the path of PyDIff/PyDiff/ when I perform inference

**Comment by limuloo** [comment]
> If I run BASICSR_EXT=True sudo $(which python) setup.py develop" in "BasicSR-light" before step 5, it shows ![image](https://user-images.githubusercontent.com/80657281/256458241-2c7487f8-229e-4399-9afc-d28da4720a36.png)

ReadTimeError, This looks like timed out error emerge when you pip install something.

**Comment by zjx1277** [comment]
Thank you for your patiently reply, I have changed the GitHub URL in the original PyDiff/BasicSR light/setup.py file to https://gitclone.com/github.com/xinntao/Basicsr After that, you can download without any timeout errors
![image](https://github.com/limuloo/PyDIff/assets/80657281/7c740a23-aed5-4854-bafa-a53e29680b7b)
