### ISSUE TITLE
大佬，能给份训练代码吗

### ISSUE THREAD

**Issue by jrcyyzb** [limuloo/PyDIff#9]

**Comment by limuloo** [comment]
您好！感谢您对我们工作的支持！附件放了训练的代码。如果还有问题依然可以通过这个邮件联系我~

如果您觉得我们的工作对您有帮助，欢迎star并引用我们~(*^▽^*)



-----原始邮件-----
发件人:jrcyyzb ***@***.***>
发送时间:2023-09-15 11:22:27 (星期五)
收件人: limuloo/PyDIff ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SPAM] [limuloo/PyDIff] 大佬，能给份训练代码吗 (Issue #9)

**Comment by limuloo** [comment]
您用学校的邮箱给我发个邮件吧，我给您发~
